#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys

mount -t 9p -o trans=virtio,version=9p2000.L,nosuid hostshare /root
sysctl -w kernel.perf_event_paranoid=1

/bin/sh